# Generated by Django 4.2 on 2023-04-27 01:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_photograph_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='photograph',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
