# Generated by Django 4.2 on 2023-05-01 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0006_photograph_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photograph',
            name='published',
            field=models.BooleanField(default=True),
        ),
    ]
